# =============================================
# 部署流水线（由 tag_deploy.yml 中的按钮触发）
# =============================================
$:
  tag_deploy.production:
    - imports:
        - https://cnb.cool/sra_lei/datacolit-secret/-/blob/main/tencent-cloud.yml
      services:
        - docker
      stages:
        - name: 构建镜像
          script: |
            docker build -f Dockerfile.prod -t ccr.ccs.tencentyun.com/sra.io/datapolit-core:${tag_name} .
            docker tag ccr.ccs.tencentyun.com/sra.io/datapolit-core:${tag_name} ccr.ccs.tencentyun.com/sra.io/datapolit-core:latest
        - name: 推送到腾讯云 CCR
          script: |
            docker login --username ${TENCENTCLOUD_DOCKER_USERNAME} --password "${TENCENTCLOUD_DOCKER_PASSWORD}" ccr.ccs.tencentyun.com
            docker push ccr.ccs.tencentyun.com/sra.io/datapolit-core:${tag_name}
            docker push ccr.ccs.tencentyun.com/sra.io/datapolit-core:latest
